apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fltk-administrator-role
# Currently, we allow every action with this ClusterRole, these could be restricted if deemed necessary.
# This will result in potential security risks on a production cluster.
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
