apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.fltk.service: fl-server-claim
  name: fl-server-claim
spec:
  # Only the Orchestrator pod should be able to write to the part. Extractor functions as a simple 'read' to
  # Make data collection easier.
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.extractor.output.size }}
  storageClassName: "nfs"
