aggregation: bulyan
attack_client: Backdoor
attack_epochs: 10
attack_server: null
backdoor_config: configs/backdoor_tasks/mnist_params_pattern.yaml
backdoor_type: 9-pixel
batch_size: 32
clients_per_round: 10
cluster: false
cluster_stored_rounds: 10
cuda: true
data_sampler: uniform
data_sampler_args:
- 5
- 42
dataset_name: fashion-mnist
defense: LeadFL
epochs: 10
experiment_prefix: Final
mal_boost: 1
mal_clients_per_round: 2
net_name: FashionMNISTCNN
num_clients: 100
num_mal_clients: 25
offload_stategy: deadline
output_location: output
pert_strength: 0.2
regular_weight: 0.4
rounds: 80
selection_method: random
single_machine: true
tensor_board_active: true
use_wandb: true
wait_for_clients: true
