orchestrator:
    cpu: 500m
    memory: 500Mi
    runtime:
      configurationFile: configuration.fltk.json
      experimentFile: experiment.fltk.json
    provided:
      configurationFile: configs/federated_tasks/example_arrival_config.json
      experimentFile: configs/example_arrival_config.json
